"""LangGraph agent state definition."""

from __future__ import annotations

from typing import Any, Optional

from typing_extensions import TypedDict

from app.models.booking import (
    ActivityOption,
    BookingCart,
    BudgetBreakdown,
    FlightOption,
    HotelOption,
    MapMarker,
    MapRoute,
)
from app.models.itinerary import Itinerary
from app.models.trip import (
    ChatMessage,
    PlanOption,
    TripRequest,
    TripStatus,
)


class ResearchResults(TypedDict, total=False):
    """Aggregated research data."""

    flights: list[FlightOption]
    trains: list[FlightOption]
    buses: list[FlightOption]
    hotels: list[HotelOption]
    activities: list[ActivityOption]
    weather: dict[str, Any]  # day -> weather summary
    routes: dict[str, Any]  # distance matrix
    travel_advisory: dict[str, Any]  # visa info, advisories
    search_queries: list[str]  # queries generated by LLM


class TripState(TypedDict, total=False):
    """Complete LangGraph state for a trip planning session."""

    # --- Identity ---
    trip_id: str

    # --- User Input ---
    request: TripRequest
    chat_history: list[ChatMessage]
    current_message: str

    # --- Status ---
    status: TripStatus
    last_checkpoint: Optional[str]  # "cp1", "cp2", "cp3"
    error: Optional[str]

    # --- Research ---
    research: ResearchResults
    research_complete: bool

    # --- Planning ---
    plan_options: list[PlanOption]
    selected_plan_id: Optional[str]
    itinerary: Optional[Itinerary]

    # --- Budget ---
    budget_breakdown: Optional[BudgetBreakdown]
    budget_feasible: bool
    budget_warnings: list[str]

    # --- Verification ---
    verification_results: list[dict]  # [{name, verified, place_id, source}]
    unverified_places: list[str]

    # --- Booking ---
    booking_cart: Optional[BookingCart]
    price_changes: list[dict]  # [{item, old_price, new_price}]

    # --- Map ---
    markers: list[MapMarker]
    routes: list[MapRoute]

    # --- Reasoning ---
    reasoning_log: list[str]
    warnings: list[str]

    # --- Checkpoint decisions ---
    checkpoint_decision: Optional[dict]
    awaiting_human: bool

    # --- Re-planning ---
    replan_request: Optional[str]
    replan_delta: Optional[dict]
    replan_analysis: Optional[dict]

    # --- Completion flags ---
    planning_complete: bool
    verification_complete: bool
    optimization_complete: bool
